echo 0 | python3 ws.py ghost.stl && echo ' - 0 '
echo 1 | python3 ws.py ghost.stl && echo ' - 1 '
echo 3 | python3 ws.py ghost.stl && echo ' - 2 '
echo 6 | python3 ws.py ghost.stl && echo ' - 3 '
echo 5 | python3 ws.py ghost.stl && echo ' - 4 '
echo 10 | python3 ws.py ghost.stl && echo ' - 5 '
echo 9 | python3 ws.py ghost.stl && echo ' - 6 '
echo 8 | python3 ws.py ghost.stl && echo ' - 7 '
echo 16 | python3 ws.py ghost.stl && echo ' - 8 '
echo 15 | python3 ws.py ghost.stl && echo ' - 9 '
echo 14 | python3 ws.py ghost.stl && echo ' - 10'
echo 13 | python3 ws.py ghost.stl && echo ' - 11'
echo 12 | python3 ws.py ghost.stl && echo ' - 12'
echo 25 | python3 ws.py ghost.stl && echo ' - 13'
echo 24 | python3 ws.py ghost.stl && echo ' - 14'
echo 23 | python3 ws.py ghost.stl && echo ' - 15'
echo 22 | python3 ws.py ghost.stl && echo ' - 16'
echo 21 | python3 ws.py ghost.stl && echo ' - 17'
echo 20 | python3 ws.py ghost.stl && echo ' - 18'
echo 19 | python3 ws.py ghost.stl && echo ' - 19'
echo 18 | python3 ws.py ghost.stl && echo ' - 20'
echo 39 | python3 ws.py ghost.stl && echo ' - 21'
echo 38 | python3 ws.py ghost.stl && echo ' - 22'
echo 37 | python3 ws.py ghost.stl && echo ' - 23'
echo 36 | python3 ws.py ghost.stl && echo ' - 24'
echo 35 | python3 ws.py ghost.stl && echo ' - 25'
echo 34 | python3 ws.py ghost.stl && echo ' - 26'
