echo 0 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 0 '
echo 1 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 1 '
echo 3 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 2 '
echo 6 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 3 '
echo 5 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 4 '
echo 10 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 5 '
echo 9 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 6 '
echo 8 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 7 '
echo 16 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 8 '
echo 15 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 9 '
echo 14 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 10'
echo 13 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 11'
echo 12 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 12'
echo 25 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 13'
echo 24 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 14'
echo 23 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 15'
echo 22 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 16'
echo 21 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 17'
echo 20 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 18'
echo 19 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 19'
echo 18 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 20'
echo 39 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 21'
echo 38 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 22'
echo 37 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 23'
echo 36 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 24'
echo 35 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 25'
echo 34 | py3 wvm_oneliner.py ghost/ghost.stl STL && echo ' - 26'
